

// this function will create the stages when a new business idea is generated by the user
async function createBusinessStages(connection, businessIdeaId) {
    try {
        // Query to get all stage IDs from Stages table
        const [stages] = await connection.execute('SELECT stage_id FROM Stages');

        if (stages.length === 0) {
            throw new Error("No stages found in the database");
        }

        // Create a Business_Stages entry for each stage
        for (const stage of stages) {
            try {
                await connection.execute(
                    'INSERT INTO Business_Stages (business_idea_id, stage_id, progress, completed) VALUES (?, ?, 0, false)',
                    [businessIdeaId, stage.stage_id]
                );
            } catch (insertError) {
                throw new Error(`Failed to insert stage ${stage.stage_id}: ${insertError.message}`);
            }
        }

        return true;
    } catch (error) {
        console.error(`Stage creation error for business idea ${businessIdeaId}:`, error);
        throw error; // Re-throw to be handled by the caller
    }
}

export { createBusinessStages }
